com:
  mu:
    format: yyyy年MM月dd日
    dbhelperautoconfiguration:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: muzuki

mu:
  log:
    enabled: true

logging:
  level:
    root: info
    com.mu: info
    org.springframework: warn